import { useState } from "react";
import Head from "next/head";
import { Bar, Line } from "react-chartjs-2";
import Spinner from "../components/Spinner";
import { useDispatch, useSelector, connect } from "react-redux";
import { getData } from "../actions";

function Home() {
  const dispatch = useDispatch();
  const state = useSelector((state) => state.bitcoin);
  const [num, setNum] = useState(15);

  const fetchData = (time) => {
    // Fetch data from redux using time
    dispatch(getData({ time, number: num }));
  };

  return (
    <div>
      <Head>
        <title>Redux - Thunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="btns-wrapper">
        <button onClick={() => fetchData("1min")}>1 Min</button>
        <button onClick={() => fetchData("5min")}>5 Min</button>
        <button onClick={() => fetchData("15min")}>15 Min</button>

        <input onChange={(e) => setNum(e.target.value)} />
      </div>
      {state.loading ? (
        <Spinner />
      ) : (
        <div className="chart-wrapper">
          <Line data={state.data} />
        </div>
      )}
    </div>
  );
}

const mapStateToProps = (state) => {
  // console.log(state);
  return { state };
};

export default connect(mapStateToProps)(Home);
